import { AlertDetailedResponse } from './models/alert-detailed-response';

export const MOCK_ALERTS: AlertDetailedResponse[] = [
  {
    // Alert 1
    id: 'ALERT-1',
    appId: 'APP-1',
    message: 'Trayport Market Data service is running normally',
    severity: "Information",
    occurrence: 1,
    status: "Active",
    occurredAt: '2025-08-20T11:58:00.000Z',
    app: {
      id: 'APP-1',
      hostName: 'DTCODEVMCSDX04W',
      appName: 'DgxEgm',
      port: '31000',
      type: 'mas-app',
      cronStartTime: '30 07 * * 1',
      cronStopTime: '00 22 * * 1',
      version: '1.0.0',
      tags: ['md-trayport-egm-uat.mcs.gem.myengie.com:31000'],
      latestStatus: {
        id: 'STATUS-1',
        appId: 'APP-1',
        status: 'Up',
        recordedAt: '2025-08-20T11:58:00.000Z',
      },
    },
  },
  {
    // Alert 2
    id: 'ALERT-2',
    appId: 'APP-2',
    message: 'PostgreSQL database memory usage is within normal limits',
    severity: "Information",
    occurrence: 1,
    status: "Active",
    occurredAt: '2025-08-20T11:59:30.000Z',
    app: {
      id: 'APP-2',
      hostName: 'DTCODEVMCSGT01W',
      appName: 'Gateway',
      port: '5432',
      type: 'database-app',
      cronStartTime: '00 06 * * *',
      cronStopTime: '00 23 * * *',
      version: '2.1.0',
      tags: ['postgresql-prod.db.myengie.com:5432', 'primary'],
      latestStatus: {
        id: 'STATUS-2',
        appId: 'APP-2',
        status: 'Up',
        recordedAt: '2025-08-20T11:59:30.000Z',
      },
    },
  },
  {
    // Alert 3 - Critical
    id: 'ALERT-3',
    appId: 'APP-3',
    message: 'API Gateway is currently unavailable',
    severity: "Error",
    occurrence: 5,
    status: "Active",
    occurredAt: '2025-08-20T10:15:00.000Z',
    app: {
      id: 'APP-3',
      hostName: 'DTCODEVMCSHP01W',
      appName: 'Horsepower-Orders',
      port: '80',
      type: 'api-gateway',
      cronStartTime: '00 00 * * *',
      cronStopTime: '23 59 * * *',
      version: '3.0.1',
      tags: ['api-gateway.myengie.com:80', 'api-gateway.myengie.com:443'],
      latestStatus: {
        id: 'STATUS-3',
        appId: 'APP-3',
        status: 'Down',
        recordedAt: '2025-08-20T10:15:00.000Z',
      },
    },
  },
  {
    // Alert 4
    id: 'ALERT-4',
    appId: 'APP-4',
    message: 'Redis Cache CPU usage is elevated',
    severity: "Warning",
    occurrence: 3,
    status: "Active",
    occurredAt: '2025-08-20T11:59:45.000Z',
    app: {
      id: 'APP-4',
      hostName: 'Redis Cache Cluster',
      appName: 'Horsepower-Trades',
      port: '6379',
      type: 'cache-app',
      cronStartTime: '00 00 * * *',
      cronStopTime: '23 59 * * *',
      version: '7.2.0',
      tags: ['redis-cache.myengie.com:6379', 'node-1'],
      latestStatus: {
        id: 'STATUS-4',
        appId: 'APP-4',
        status: 'Up',
        recordedAt: '2025-08-20T11:59:45.000Z',
      },
    },
  },
  {
    // Alert 5
    id: 'ALERT-5',
    appId: 'APP-5',
    message: 'RabbitMQ message queue is responding normally',
    severity: "Information",
    occurrence: 1,
    status: "Resolved",
    occurredAt: '2025-08-20T11:57:00.000Z',
    app: {
      id: 'APP-5',
      hostName: 'DTCODEVMCSMELW',
      appName: 'Feedchecker-TGE',
      port: '5672',
      type: 'message-queue',
      cronStartTime: '00 05 * * *',
      cronStopTime: '23 55 * * *',
      version: '3.12.0',
      tags: ['rabbitmq.myengie.com:5672', 'rabbitmq-mgmt.myengie.com:15672'],
      latestStatus: {
        id: 'STATUS-5',
        appId: 'APP-5',
        status: 'Up',
        recordedAt: '2025-08-20T11:57:00.000Z',
      },
    },
  },
];
