import { ConnectionResponse } from '../../core/models/responses/connection-response';
import { ConnectionDetailedResponse } from '../../core/models/responses/connection-detailed-response';

export const MOCK_CONNECTIONS: ConnectionDetailedResponse[] = [
 {
    // Connection 1
    id: 'CONN-1',
    clientId: 'CLIENT-1',
    serverId: 'SERVER-1',
    application: 'DgxEgm',
    apiVersion: '1.0.0',
    machine: 'WORKSTATION-001',
    processId: '4532',
    client: {
      id: 'CLIENT-1',
      login: 'john.doe@engie.com',
      gaia: 'GAIA-12345',
    },
    server: {
      id: 'SERVER-1',
      hostName: 'DTCODEVMCSDX04W',
      appName: 'DgxEgm',
      port: '31000',
      type: 'mas-server',
      cronStartTime: '30 07 * * 1',
      cronStopTime: '00 22 * * 1',
      version: '1.0.0',
      tags: ['md-trayport-egm-uat.mcs.gem.myengie.com:31000'],
      latestStatus: {
        id: 'STATUS-1',
        serverId: 'SERVER-1',
        status: 'Up',
        recordedAt: '2025-08-20T11:58:00.000Z',
      },
    },
  },
  {
    // Connection 2
    id: 'CONN-2',
    clientId: 'CLIENT-2',
    serverId: 'SERVER-2',
    application: 'Gateway',
    apiVersion: '2.1.0',
    machine: 'WORKSTATION-002',
    processId: '5891',
    client: {
      id: 'CLIENT-2',
      login: 'marie.smith@engie.com',
      gaia: 'GAIA-67890',
    },
    server: {
      id: 'SERVER-2',
      hostName: 'DTCODEVMCSGT01W',
      appName: 'Gateway',
      port: '5432',
      type: 'database-server',
      cronStartTime: '00 06 * * *',
      cronStopTime: '00 23 * * *',
      version: '2.1.0',
      tags: ['postgresql-prod.db.myengie.com:5432', 'primary'],
      latestStatus: {
        id: 'STATUS-2',
        serverId: 'SERVER-2',
        status: 'Up',
        recordedAt: '2025-08-20T11:59:30.000Z',
      },
    },
  },
  {
    // Connection 3
    id: 'CONN-3',
    clientId: 'CLIENT-3',
    serverId: 'SERVER-3',
    application: 'Horsepower-Orders',
    apiVersion: '3.0.1',
    machine: 'WORKSTATION-003',
    processId: '7234',
    client: {
      id: 'CLIENT-3',
      login: 'pierre.martin@engie.com',
      gaia: 'GAIA-11223',
    },
    server: {
      id: 'SERVER-3',
      hostName: 'DTCODEVMCSHP01W',
      appName: 'Horsepower-Orders',
      port: '80',
      type: 'api-gateway',
      cronStartTime: '00 00 * * *',
      cronStopTime: '23 59 * * *',
      version: '3.0.1',
      tags: ['api-gateway.myengie.com:80', 'api-gateway.myengie.com:443'],
      latestStatus: {
        id: 'STATUS-3',
        serverId: 'SERVER-3',
        status: 'Down',
        recordedAt: '2025-08-20T10:15:00.000Z',
      },
    },
  },
  {
    // Connection 4
    id: 'CONN-4',
    clientId: 'CLIENT-4',
    serverId: 'SERVER-4',
    application: 'Horsepower-Trades',
    apiVersion: '7.2.0',
    machine: 'SERVER-TRADE-01',
    processId: '9876',
    client: {
      id: 'CLIENT-4',
      login: 'sophie.durand@engie.com',
      gaia: 'GAIA-44556',
    },
    server: {
      id: 'SERVER-4',
      hostName: 'Redis Cache Cluster',
      appName: 'Horsepower-Trades',
      port: '6379',
      type: 'cache-server',
      cronStartTime: '00 00 * * *',
      cronStopTime: '23 59 * * *',
      version: '7.2.0',
      tags: ['redis-cache.myengie.com:6379', 'node-1'],
      latestStatus: {
        id: 'STATUS-4',
        serverId: 'SERVER-4',
        status: 'Up',
        recordedAt: '2025-08-20T11:59:45.000Z',
      },
    },
  },
  {
    // Connection 5
    id: 'CONN-5',
    clientId: 'CLIENT-5',
    serverId: 'SERVER-5',
    application: 'Feedchecker-TGE',
    apiVersion: '3.12.0',
    machine: 'MESSAGE-QUEUE-01',
    processId: '3456',
    client: {
      id: 'CLIENT-5',
      login: 'luc.bernard@engie.com',
      gaia: 'GAIA-77889',
    },
    server: {
      id: 'SERVER-5',
      hostName: 'DTCODEVMCSMELW',
      appName: 'Feedchecker-TGE',
      port: '5672',
      type: 'message-queue',
      cronStartTime: '00 05 * * *',
      cronStopTime: '23 55 * * *',
      version: '3.12.0',
      tags: ['rabbitmq.myengie.com:5672', 'rabbitmq-mgmt.myengie.com:15672'],
      latestStatus: {
        id: 'STATUS-5',
        serverId: 'SERVER-5',
        status: 'Up',
        recordedAt: '2025-08-20T11:57:00.000Z',
      },
    },
  },
];
