import { ConnectionResponse } from '../connections/models/connection-response';
import { AppDetailedResponse } from './models/app-detailed-response';
import { AppStatusResponse } from '../app-statuses/models/app-status-response';

export const MOCK_APPS: AppDetailedResponse[] = [
  {
    // App 1 - Trayport Market Data
    id: 'APP-1',
    hostName: 'Trayport',
    version: '1.0.0',
    port: '31000',
    appName: 'TrayportMarketDataEgm',
    type: 'mas-app',
    cronStartTime: '30 07 * * 1',
    cronStopTime: '00 22 * * 1',
    tags: ['md-trayport-egm-uat','mcs.gem.myengie.com:31000'],
    latestStatus: {
      id: 'APPSTATUS-LAST-1',
      recordedAt: '2025-08-20T11:58:00.000Z',
      appId: 'APP-1',
      status: 'Up',
    } as AppStatusResponse,
    connections: [
      {
        id: 'CONNECTION-1A',
        clientGaia: 'CLIENT-TRAY-1',
        clientLogin: 'trayport@myengie.com',
        appId: 'APP-1',
        application: 'dotnet',
        apiVersion: '1.0.0',
        machine: 'trayport-machine-1',
        processId: '1234',
      } as ConnectionResponse,
    ],
    statuses: [
      {
        id: 'APPSTATUS-1A',
        streak: 5,
        recordedAt: '2025-08-20T11:58:00.000Z',
        appId: 'APP-1',
        status: 'Up',
      } as AppStatusResponse,
    ],
  },
  {
    // App 2 - PostgreSQL Database
    id: 'APP-2',
    hostName: 'DatabaseApp',
    version: '2.1.0',
    port: '5432',
    appName: 'PostgreSQLService',
    type: 'database-app',
    cronStartTime: '00 06 * * *',
    cronStopTime: '00 23 * * *',
    tags: ['postgresql-prod.db.myengie.com:5432'],
    latestStatus: {
      id: 'APPSTATUS-LAST-2',
      streak: 25,
      recordedAt: '2025-08-20T11:59:30.000Z',
      appId: 'APP-2',
      status: 'Up',
    } as AppStatusResponse,
    connections: [
      {
        id: 'CONNECTION-2A',
        clientGaia: 'CLIENT-DB-1',
        clientLogin: 'db1@myengie.com',
        appId: 'APP-2',
        application: 'postgresql',
        apiVersion: '2.1.0',
        machine: 'db-machine-1',
        processId: '5678',
      } as ConnectionResponse,
      {
        id: 'CONNECTION-2B',
        clientGaia: 'CLIENT-DB-2',
        clientLogin: 'db2@myengie.com',
        appId: 'APP-2',
        application: 'postgresql',
        apiVersion: '2.1.0',
        machine: 'db-machine-2',
        processId: '5679',
      } as ConnectionResponse,
    ],
    statuses: [
      {
        id: 'APPSTATUS-2A',
        streak: 8,
        recordedAt: '2025-08-20T11:59:30.000Z',
        appId: 'APP-2',
        status: 'Up',
      } as AppStatusResponse,
    ],
  },
  {
    // App 3 - API Gateway (Problématique)
    id: 'APP-3',
    hostName: 'APIGateway test test',
    version: '3.0.1',
    port: '80',
    appName: 'NginxAPIGateway',
    type: 'api-gateway',
    cronStartTime: '00 00 * * *',
    cronStopTime: '23 59 * * *',
    tags: ['api-gateway.myengie.com:80', 'api-gateway.myengie.com:443'],
    latestStatus: {
      id: 'APPSTATUS-3A',
      recordedAt: '2025-08-20T10:15:00.000Z',
      appId: 'APP-3',
      status: 'Down',
    },
    connections: [
      {
        id: 'CONNECTION-3A',
        clientGaia: 'CLIENT-GATEWAY-1',
        clientLogin: 'gateway@myengie.com',
        appId: 'APP-3',
        application: 'nginx',
        apiVersion: '3.0.1',
        machine: 'gateway-1',
        processId: '9999',
      } as ConnectionResponse,
    ],
    statuses: [
      {
        id: 'APPSTATUS-3A',
        recordedAt: '2025-08-20T10:15:00.000Z',
        appId: 'APP-3',
        status: 'Down',
      } as AppStatusResponse,
    ],
  },

  {
    // App 4 - Redis Cache
    id: 'APP-4',
    hostName: 'RedisCache',
    version: '7.2.0',
    port: '6379',
    appName: 'RedisCacheService',
    type: 'cache-app',
    cronStartTime: '00 00 * * *',
    cronStopTime: '23 59 * * *',
    tags: ['redis-cache.myengie.com:6379'],
    latestStatus: {
      id: 'APPSTATUS-LAST-4',
      streak: 42,
      recordedAt: '2025-08-20T11:59:45.000Z',
      appId: 'APP-4',
      status: 'Up',
    } as AppStatusResponse,
    connections: [
      {
        id: 'CONNECTION-4A',
        clientGaia: 'CLIENT-CACHE-1',
        clientLogin: 'cache1@myengie.com',
        appId: 'APP-4',
        application: 'redis',
        apiVersion: '7.2.0',
        machine: 'cache-machine-1',
        processId: '7777',
      } as ConnectionResponse,
      {
        id: 'CONNECTION-4B',
        clientGaia: 'CLIENT-CACHE-2',
        clientLogin: 'cache2@myengie.com',
        appId: 'APP-4',
        application: 'redis',
        apiVersion: '7.2.0',
        machine: 'cache-machine-2',
        processId: '7778',
      } as ConnectionResponse,
      {
        id: 'CONNECTION-4C',
        clientGaia: 'CLIENT-CACHE-3',
        clientLogin: 'cache3@myengie.com',
        appId: 'APP-4',
        application: 'redis',
        apiVersion: '7.2.0',
        machine: 'cache-machine-3',
        processId: '7779',
      } as ConnectionResponse,
    ],
    statuses: [
      {
        id: 'APPSTATUS-4A',
        streak: 12,
        recordedAt: '2025-08-20T11:59:45.000Z',
        appId: 'APP-4',
        status: 'Up',
      } as AppStatusResponse,
    ],
  },

  {
    // App 5 - Message Queue (RabbitMQ)
    id: 'APP-5',
    hostName: 'MessageQueue',
    version: '3.12.0',
    port: '5672',
    appName: 'RabbitMQService',
    type: 'message-queue',
    cronStartTime: '00 05 * * *',
    cronStopTime: '23 55 * * *',
    tags: ['rabbitmq.myengie.com:5672', 'rabbitmq-mgmt.myengie.com:15672'],
    latestStatus: {
      id: 'APPSTATUS-LAST-5',
      streak: 3,
      recordedAt: '2025-08-20T11:57:00.000Z',
      appId: 'APP-5',
      status: 'Up',
    } as AppStatusResponse,
    connections: [
      {
        id: 'CONNECTION-5A',
        clientGaia: 'CLIENT-QUEUE-1',
        clientLogin: 'queue@myengie.com',
        appId: 'APP-5',
        application: 'rabbitmq',
        apiVersion: '3.12.0',
        machine: 'queue-machine-1',
        processId: '8888',
      } as ConnectionResponse,
    ],
    statuses: [
      {
        id: 'APPSTATUS-5A',
        streak: 2,
        recordedAt: '2025-08-20T11:57:00.000Z',
        appId: 'APP-5',
        status: 'Up',
      } as AppStatusResponse,
      {
        id: 'APPSTATUS-5B',
        streak: 1,
        recordedAt: '2025-08-20T11:56:00.000Z',
        appId: 'APP-5',
        status: 'Up',
      } as AppStatusResponse,
    ],
  },

  {
    // App 6 - Message Queue (RabbitMQ)
    id: 'APP-6',
    hostName: 'MessageQueue',
    version: '3.12.0',
    port: '5672',
    appName: 'RabbitMQService',
    type: 'message-queue',
    cronStartTime: '00 05 * * *',
    cronStopTime: '23 55 * * *',
    tags: ['rabbitmq.myengie.com:5672', 'rabbitmq-mgmt.myengie.com:15672'],
    latestStatus: {
      id: 'APPSTATUS-LAST-6',
      streak: 3,
      recordedAt: '2025-08-20T11:57:00.000Z',
      appId: 'APP-6',
      status: 'Up',
    } as AppStatusResponse,
    connections: [
      {
        id: 'CONNECTION-6A',
        clientGaia: 'CLIENT-QUEUE-1',
        clientLogin: 'queue@myengie.com',
        appId: 'APP-6',
        application: 'rabbitmq',
        apiVersion: '3.12.0',
        machine: 'queue-machine-1',
        processId: '8888',
      } as ConnectionResponse,
    ],
    statuses: [
      {
        id: 'APPSTATUS-5A',
        streak: 2,
        recordedAt: '2025-08-20T11:57:00.000Z',
        appId: 'APP-5',
        status: 'Up',
      } as AppStatusResponse,
      {
        id: 'APPSTATUS-5B',
        streak: 1,
        recordedAt: '2025-08-20T11:56:00.000Z',
        appId: 'APP-5',
        status: 'Up',
      } as AppStatusResponse,
    ],
  },
];
